navbar-links:
    Archive: /archives
    About: /about.html

avatar: /hexo.png
favicon: /hexo.png

header:
    title: "Beautiful Hexo"
    motto: Build a beautiful and simple website in minutes
    bigimgs:
        - src: /bigimgs/01.jpg
          desc: beautiful island
        - src: /bigimgs/02.jpg
          desc: Tropical Fish
        - src: /bigimgs/03.jpg
          desc: ocean

rss: /atom.xml
googlefonts:
  - "Lora:400,700,400italic,700italic"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"

footer:
  facebook:
    link: # your link e.g. https://...
    title: Facebook
    icon: fa-facebook
    enalbe: false
  weibo:
    link: 'http://weibo.com/bisyao?is_all=1'
    title: Weibo
    icon: fa-weibo
    enalbe: true
  github:
    link: 'https://github.com/twoyao'
    title: GitHub
    icon: fa-github
    enable: true
  rss:
    link: '/atom.xml'
    title: RSS
    icon: fa-rss
    enable: true
  twitter:
    link: 'https://twitter.com/twoyao_'
    title: Twitter
    icon: fa-twitter
    enable: true
  mail:
    link: 'mailto:bisyao@gmail.com'
    title: Email me
    icon: fa-envelope
    enable: true
  linkin:
    link: # your link here e.g. http...
    title: LinkedIn
    icon: fa-linkedin
    enable: false
  stackoverflow:
    link: # your link here e.g. http...
    title: StackOverflow
    icon: fa-stack-overflow
    enable: false

google_analytics:

comment:
  enable: true
  disqus: twoyao

